export const breadcrumbsObj: Record<string, string> = {
    '/': 'Главная',
    'the-juiciest': 'Самое сочное',
    vegan: 'Веганская кухня',
    snacks: 'Закуски',
    courses: 'Первые блюда',
    'second-dish': 'Вторые блюда',
    'side-dishes': 'Гарниры',
    deserts: 'Десерты',
    bakery: 'Выпечка',
    'raw-food': 'Сыроедческие блюда',
    drinks: 'Напитки',
    national: 'Национальные',
    salads: 'Салаты',
};
